/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-05-20 19:09:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.gcetminiwebproject.models.BusModel;
import java.sql.ResultSet;

public final class AddNewBus_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.gcetminiwebproject.models.BusModel");
    _jspx_imports_classes.add("java.sql.ResultSet");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Session validation for bus operator  -->\n");

	if(session.getAttribute("type")==null || (!session.getAttribute("type").equals("busoperator"))){
		response.sendRedirect("BusOperatorLogin.jsp");
	}

      out.write("\n");
      out.write("<!-- session validation ends -->\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "layout/Header.jsp", out, false);
      out.write("\n");
      out.write("<!-- ***********   START   *********** -->\n");
      out.write("\n");
      out.write("<div class=\"main-body\" >\n");
      out.write("\n");
      out.write("<div class=\"left-column \">\n");
      out.write("	<ul>\n");
      out.write("		<li><a href=\"AddNewBus.jsp\">Add new bus</a>\n");
      out.write("		</li>\n");
      out.write("		<li><a href=\"GetAddedBuses.jsp\">Show buses</a>\n");
      out.write("		</li>\n");
      out.write("		<li><a href=\"Logout.jsp\">Logout</a>\n");
      out.write("		</li>\n");
      out.write("	</ul>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"mymainWrapper\">\n");
      out.write("	<div class=\"centerformWrapper\">\n");
      out.write("		<div class=\"centertitle\">\n");
      out.write("			Add new bus\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("		<div class=\"errordiv \">\n");
      out.write("			");

				if (request.getParameter("msg") != null) {
			
      out.write("\n");
      out.write("			<h4>");
      out.print(request.getParameter("msg"));
      out.write("</h4>\n");
      out.write("			");

				}
			
      out.write("\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("		<div class=\"centerform \">\n");
      out.write("			<form name=\"myForm\" action=\"AddNewBusController\"\n");
      out.write("				onsubmit=\"return validateLogin();\" method=\"post\">\n");
      out.write("				<div class=\"formgroup\">\n");
      out.write("					<label for=\"busname\">Enter Bus Name</label> <input type=\"text\"\n");
      out.write("						name=\"busname\" class=\"formcontrol\" />\n");
      out.write("				</div>\n");
      out.write("				<div class=\"formgroup\">\n");
      out.write("					<label for=\"bustype\">Enter Bus Type</label> \n");
      out.write("					<select name=\"bustype1\" class=\"formcontrol\" style = \"margin-bottom: 10px;\">\n");
      out.write("						<option Value=\"AC\">AC</option>\n");
      out.write("						<option Value=\"Non-AC\">Non-AC</option>\n");
      out.write("					</select>\n");
      out.write("					\n");
      out.write("					 <label for=\"bustype2\"> </label>\n");
      out.write("					 <select name=\"bustype2\"\n");
      out.write("						class=\"formcontrol\">\n");
      out.write("						<option Value=\"Non-Sleeper\">NonSleeper</option>\n");
      out.write("						<option Value=\"Sleeper\">Sleeper</option>\n");
      out.write("						<option Value=\"Semi-Sleeper\">SemiSleeper</option>\n");
      out.write("					</select>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"formgroup\">\n");
      out.write("					<label for=\"departurecity\">Enter Departure City </label> <input\n");
      out.write("						type=\"text\" name=\"departurecity\" class=\"formcontrol\" />\n");
      out.write("				</div>\n");
      out.write("				<div class=\"formgroup\">\n");
      out.write("					<label for=\"arrivalcity\">Enter Arrival City </label> <input\n");
      out.write("						type=\"text\" name=\"arrivalcity\" class=\"formcontrol\" />\n");
      out.write("				</div>\n");
      out.write("				<div class=\"formgroup\">\n");
      out.write("					<label for=\"departuretime\">Enter Departure Time in 24Hr\n");
      out.write("						format</label> <input type=\"text\" name=\"departuretime\"\n");
      out.write("						class=\"formcontrol\" />\n");
      out.write("				</div>\n");
      out.write("				<div class=\"formgroup\">\n");
      out.write("					<label for=\"traveltime\">Enter Travel Time in 24-hr\n");
      out.write("						format(HH:MM) </label> <input type=\"text\" name=\"traveltime\"\n");
      out.write("						class=\"formcontrol\" />\n");
      out.write("				</div>\n");
      out.write("				<div class=\"formgroup\">\n");
      out.write("					<label for=\"operatingdays\">Enter Operating Days </label><br /> <input\n");
      out.write("						type=\"checkbox\" name=\"OperatingDays1\" value=\"S\" checked>Sunday<br />\n");
      out.write("					<input type=\"checkbox\" name=\"OperatingDays2\" value=\"M\">Monday<br />\n");
      out.write("					<input type=\"checkbox\" name=\"OperatingDays3\" value=\"T\">Tuesday<br />\n");
      out.write("					<input type=\"checkbox\" name=\"OperatingDays4\" value=\"W\">Wednesday<br />\n");
      out.write("					<input type=\"checkbox\" name=\"OperatingDays5\" value=\"T\">Thursday<br />\n");
      out.write("					<input type=\"checkbox\" name=\"OperatingDays6\" value=\"F\">Friday<br />\n");
      out.write("					<input type=\"checkbox\" name=\"OperatingDays7\" value=\"S\">Saturday<br />\n");
      out.write("				</div>\n");
      out.write("				<div class=\"formgroup\">\n");
      out.write("					<label for=\"cost\">Cost of travel</label> <input type=\"text\"\n");
      out.write("						name=\"cost\" class=\"formcontrol\" />\n");
      out.write("				</div>\n");
      out.write("				<div class=\"formgroup\">\n");
      out.write("					<label for=\"Number of Seats\">Number of Seats </label> <input\n");
      out.write("						type=\"text\" name=\"seats\" class=\"formcontrol\" />\n");
      out.write("				</div>\n");
      out.write("				<div class=\"formgroup\">\n");
      out.write("					<input type=\"submit\" class=\"btn btnsuccess\" value=\"Add\" style=\"float:left;\" /> \n");
      out.write("					<input type=\"reset\" class=\"btn btndanger\" value=\"Cancel\" style=\"float:right;\" />\n");
      out.write("				</div>\n");
      out.write("			</form>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("<!-- ********************************* -->\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "layout/Footer.jsp", out, false);
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
