/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-05-14 01:52:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import javax.servlet.http.*;
import com.gcetminiwebproject.models.BusModel;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.gcetminiwebproject.models.BusModel");
    _jspx_imports_classes.add("java.sql.ResultSet");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--for form validation-->\r\n");
      out.write("<script type=\"text/javascript\" src=\"assets/js/blank.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"assets/js/jquery.min.js\" type=\"text/javascript\"></script> \r\n");
      out.write("<script src=\"assets/js/liquidmetal.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"assets/js/jquery.flexselect.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    $(document).ready(function () {\r\n");
      out.write("        $(\"select.flexselect\").flexselect();\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!--for calender-->\r\n");
      out.write("<script>\r\n");
      out.write("    jQuery(function () {\r\n");
      out.write("        jQuery(\"#inf_custom_someDateField\").datepicker();\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    document.onkeydown = function (event) {\r\n");
      out.write("\r\n");
      out.write("        if (!event) { /* This will happen in IE */\r\n");
      out.write("            event = window.event;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        var keyCode = event.keyCode;\r\n");
      out.write("\r\n");
      out.write("        if (keyCode == 8 &&\r\n");
      out.write("                ((event.target || event.srcElement).tagName != \"TEXTAREA\") &&\r\n");
      out.write("                ((event.target || event.srcElement).tagName != \"INPUT\")) {\r\n");
      out.write("\r\n");
      out.write("            if (navigator.userAgent.toLowerCase().indexOf(\"msie\") == -1) {\r\n");
      out.write("                event.stopPropagation();\r\n");
      out.write("            } else {\r\n");
      out.write("                alert(\"prevented\");\r\n");
      out.write("                event.returnValue = false;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("    };\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "layout/Header.jsp", out, false);
      out.write("\r\n");
      out.write("<div  class=\"errordiv \">\r\n");
      out.write("        ");

            if (request.getParameter("msg") != null) {
        
      out.write("\r\n");
      out.write("        <h4 style=\"color:black;\">");
      out.print(request.getParameter("msg"));
      out.write("</h4>\r\n");
      out.write("        ");

            }
        
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("<!-- ***********   START   *********** -->\r\n");
      out.write("\r\n");
      out.write("<!--show message coming from java class-->\r\n");
      out.write("<div class=\"myWrapper \">\r\n");
      out.write("\r\n");
      out.write("    <!--searching bus-->\r\n");
      out.write("    <div class=\"leftWrapper \">\r\n");
      out.write("        <div class=\"centertitle\">\r\n");
      out.write("            CHOOSE YOUR DESTINATION</div>\r\n");
      out.write("        <div class=\"col-lg-offset-2\">\r\n");
      out.write("            <form name=\"SearchBusFormController\" action=\"SearchBusFormController\"\r\n");
      out.write("                  onsubmit=\"return validateLogin12();\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"formgroup \">\r\n");
      out.write("                    <label for=\"from\">From</label>\r\n");
      out.write("                    <select name=\"from\" id=\"from\" class=\"formcontrol\">						\r\n");
      out.write("                        <option value=\"\"></option>\r\n");
      out.write("                        ");

                            BusModel model = new BusModel();
                            ResultSet rs = model.getBusInfo1(1);

                            while (rs.next()) {
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <option value=\"");
      out.print(rs.getString(1));
      out.write('"');
      out.write('>');
      out.print(rs.getString(1).toUpperCase());
      out.write("</option>\r\n");
      out.write("                        ");
} 
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"formgroup\">\r\n");
      out.write("                    <label for=\"to\">To</label>\r\n");
      out.write("                    <select name=\"to\" id=\"to\" class=\"formcontrol\">\r\n");
      out.write("                        <option value=\"\"></option>\r\n");
      out.write("                        ");

                            ResultSet rs1 = model.getBusInfo1(2);

                            while (rs1.next()) {
      out.write("\r\n");
      out.write("                        <option value=\"");
      out.print(rs1.getString(1));
      out.write('"');
      out.write('>');
      out.print(rs1.getString(1).toUpperCase());
      out.write("</option>\r\n");
      out.write("                        ");
}
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"formgroup \">\r\n");
      out.write("                    <label for=\"from\">Date</label>\r\n");
      out.write("                    <!-- <input type=\"text\"\r\n");
      out.write("                            class=\"formcontrol\" id=\"date\" name=\"date\"> -->\r\n");
      out.write("                    <input class=\"tcal formcontrol\" type=\"text\" name=\"date\" />\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"formgroup \">\r\n");
      out.write("                    <button type=\"submit\"\r\n");
      out.write("                            class=\"btn btnsuccess \"\r\n");
      out.write("                            style=\"float: left\">Search Buses</button>\r\n");
      out.write("                    <button type=\"reset\"\r\n");
      out.write("                            class=\"btn btnwarning \"\r\n");
      out.write("                            style=\"float: right\">Clear</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--  End of left wrapper -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!--Login Part-->\r\n");
      out.write("    <div class=\"rightWrapper\">\r\n");
      out.write("        <div class=\"centertitle\">\r\n");
      out.write("            LOGIN</div>\r\n");
      out.write("        <div class=\"\">\r\n");
      out.write("            <form name=\"LoginFormController\" action=\"LoginFormController\"\r\n");
      out.write("                  onsubmit=\"return validateLogin13();\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"formgroup\">\r\n");
      out.write("                    <label for=\"from\">Email</label> <input type=\"text\" id=\"email\"\r\n");
      out.write("                                                           class=\"formcontrol text required email\" id=\"email\"\r\n");
      out.write("                                                           name=\"username\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"formgroup\">\r\n");
      out.write("                    <label for=\"password\">Password</label> <input type=\"password\"\r\n");
      out.write("                                                                  class=\"formcontrol\" id=\"password\" name=\"password\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"formgroup\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"type\" value=\"user\" />\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"formgroup\">\r\n");
      out.write("                    <button type=\"submit\"\r\n");
      out.write("                            class=\"btn btnsuccess\"\r\n");
      out.write("                            style=\"float: left\">Login</button>\r\n");
      out.write("                    <button type=\"reset\"\r\n");
      out.write("                            class=\"btn btnwarning\"\r\n");
      out.write("                            style=\"float: right\">Clear</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"logOptions\">\r\n");
      out.write("            <a href=\"RegisterUser.jsp\"> Sign Up</a> <span>|</span> <a href=\"AdminLogin.jsp\">Admin Login</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "layout/Footer.jsp", out, false);
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
