/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-05-14 01:31:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.gcetminiwebproject.models.BusModel;
import java.sql.ResultSet;

public final class RegisterUser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.gcetminiwebproject.models.BusModel");
    _jspx_imports_classes.add("java.sql.ResultSet");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ***********   START   *********** -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "layout/Header.jsp", out, false);
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"assets/js/blank.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"myWrapper\">\r\n");
      out.write("    <div class=\"centerformWrapper\">\r\n");
      out.write("        <div class=\"centertitle \">\r\n");
      out.write("            REGISTER FORM\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"errordiv\">\r\n");
      out.write("            ");

                String msg = request.getParameter("msg");
                if (msg != null) {
                    out.print(msg);
                }
            
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!--User Registration-->\r\n");
      out.write("        <div class=\"centerform\">\r\n");
      out.write("            <form name=\"RegisterUserController\" action=\"RegisterUserController\"\r\n");
      out.write("                  onsubmit=\"return validateLogin15();\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"formgroup\">\r\n");
      out.write("                    <label for=\"username\">Email ID</label> \r\n");
      out.write("                    <input type=\"text\" name=\"username\" class=\"formcontrol\"/>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"formgroup\">\r\n");
      out.write("                    <label for=\"password\">Password</label> \r\n");
      out.write("                    <input type=\"password\" name=\"password\" placeholder=\"at least 5 character\" class=\"formcontrol\"/>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"formgroup\">\r\n");
      out.write("                    <label for=\"confirmPassword\">Confirm Password</label> \r\n");
      out.write("                    <input type=\"password\" name=\"confirmPassword\" class=\"formcontrol\"/>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"formgroup\">\r\n");
      out.write("                    <label for=\"fName\">First Name</label> \r\n");
      out.write("                    <input type=\"text\" name=\"fName\" class=\"formcontrol\"/>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"formgroup\">\r\n");
      out.write("                    <label for=\"lName\">Last Name</label> \r\n");
      out.write("                    <input type=\"text\" name=\"lName\" class=\"formcontrol\"/>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"formgroup\">\r\n");
      out.write("                    <label for=\"city\">City</label> \r\n");
      out.write("                    <input type=\"text\" name=\"city\" class=\"formcontrol\"/>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"formgroup\">\r\n");
      out.write("                    <label for=\"address\">Address</label> \r\n");
      out.write("                    <textarea name=\"address\" class=\"formcontrol\" rows=\"3\"></textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"formgroup\">\r\n");
      out.write("                    <label for=\"phoneNumber\">Phone Number</label> \r\n");
      out.write("                    <input type=\"text\" name=\"phoneNumber\" class=\"formcontrol\"/>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"formgroup buttoncenter\">\r\n");
      out.write("                   <button type=\"submit\" class=\"btnsuccess\">Submit</button>\r\n");
      out.write("                    <button type=\"reset\" class=\"btn btnwarning\">Reset</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ********************************* -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "layout/Footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
