/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-05-19 07:32:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.cognizant.model.BusOperatorModel;
import java.sql.ResultSet;
import com.cognizant.model.UserModel;

public final class EditProfile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("com.cognizant.model.BusOperatorModel");
    _jspx_imports_classes.add("com.cognizant.model.UserModel");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	<!-- Session validation for bus operator  -->\n");

	if(session.getAttribute("type")==null ){
		response.sendRedirect("index.jsp");
	}

      out.write("\n");
      out.write("<!-- session validation ends -->\n");
      out.write("	\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "layout/Header.jsp", out, false);
      out.write('\n');

	if (session.getAttribute("type").equals("user")) {

      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "layout/UserSidebar.jsp", out, false);
      out.write('\n');

	} else {

      out.write("\n");
      out.write("<div class=\"left-column col-lg-3 col-md-3 col-sm-3 col-xs-3\">\n");
      out.write("	<ul>\n");
      out.write("		<li><a href=\"AddNewBus.jsp\">Add new bus</a>\n");
      out.write("		</li>\n");
      out.write("		<li><a href=\"GetAddedBuses.jsp\">Show buses</a>\n");
      out.write("		</li>\n");
      out.write("		<li><a href=\"EditProfile.jsp\">Edit profile</a>\n");
      out.write("		</li>\n");
      out.write("		<li><a href=\"ChangePassword.jsp\">Change Password</a>\n");
      out.write("		</li>\n");
      out.write("		<li><a href=\"DeleteBusOperator.jsp\">Delete account</a>\n");
      out.write("		</li>\n");
      out.write("		<li><a href=\"Logout.jsp\">Logout</a>\n");
      out.write("		</li>\n");
      out.write("	</ul>\n");
      out.write("</div>\n");

	}

      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"assets/js/blank.js\"></script>\n");
      out.write("\n");
      out.write("<!-- ***********   START   *********** -->\n");
      out.write("<div class=\"mymainWrapper col-lg-9 col-md-9 col-sm-12 col-xs-12\">\n");
      out.write("	<div class=\"centerformWrapper col-lg-6 col-md-6 col-sm-12 col-xs-4\">\n");
      out.write("		<div class=\"centertitle row col-lg-12 col-md-12 col-sm-12 col-xs-12\">\n");
      out.write("			EDIT PROFILE</div>\n");
      out.write("		<div class=\"errordiv col-lg-10 col-md-10 col-sm-10 col-xs-10\">\n");
      out.write("			");

				try {
					if (request.getParameter("msg") != null) {
						out.print("<div>" + request.getParameter("msg") + "</div>");
					}
				} catch (Exception e) {
					out.print("some error occured..");
				}
			
      out.write("\n");
      out.write("		</div>\n");
      out.write("		");

			if (session.getAttribute("type").equals("user")) {
				UserModel um = new UserModel();
				um.setUserID(String.valueOf(session.getAttribute("userid")));
				ResultSet rs = um.getUserData();
				while (rs.next()) {
		
      out.write("\n");
      out.write("		<div class=\"centerform col-lg-12 col-md-12 col-sm-12c col-xs-12\">\n");
      out.write("			<form name=\"EditProfileFormController\"\n");
      out.write("				action=\"EditProfileFormController\"\n");
      out.write("				onsubmit=\"return validateLogin9();\" method=\"post\">\n");
      out.write("\n");
      out.write("				<div class=\"form-group\">\n");
      out.write("					<label for=\"firstname\">FirstName</label> <input type=\"text\"\n");
      out.write("						name=\"firstname\" class=\"form-control\" value=\"");
      out.print(rs.getString(2));
      out.write("\" />\n");
      out.write("				</div>\n");
      out.write("				<div class=\"form-group\">\n");
      out.write("					<label for=\"lastname\">LastName</label> <input type=\"text\"\n");
      out.write("						name=\"lastname\" class=\"form-control\" value=\"");
      out.print(rs.getString(3));
      out.write("\" />\n");
      out.write("				</div>\n");
      out.write("				<div class=\"form-group\">\n");
      out.write("					<label for=\"address\">Address</label> <input type=\"text\"\n");
      out.write("						name=\"address\" class=\"form-control\" value=\"");
      out.print(rs.getString(4));
      out.write("\" />\n");
      out.write("				</div>\n");
      out.write("				<div class=\"form-group\">\n");
      out.write("					<label for=\"city\">City</label> <input type=\"text\" name=\"city\"\n");
      out.write("						class=\"form-control\" value=\"");
      out.print(rs.getString(5));
      out.write("\" />\n");
      out.write("				</div>\n");
      out.write("				<div class=\"form-group\">\n");
      out.write("					<label for=\"email\">EMail</label> <input type=\"text\" name=\"email\"\n");
      out.write("						class=\"form-control\" value=\"");
      out.print(rs.getString(6));
      out.write("\" />\n");
      out.write("				</div>\n");
      out.write("				<div class=\"form-group\">\n");
      out.write("					<label for=\"phonenumber\">Phone Number</label> <input type=\"text\"\n");
      out.write("						name=\"phonenumber\" class=\"form-control\"\n");
      out.write("						value=\"");
      out.print(rs.getString(7));
      out.write("\" />\n");
      out.write("				</div>\n");
      out.write("				<div class=\"form-group\">\n");
      out.write("					<button type=\"submit\" class=\"btn btn-danger\">Update</button>\n");
      out.write("				</div>\n");
      out.write("			</form>\n");
      out.write("			");

				}
					rs.close();
				} else {
					BusOperatorModel bom = new BusOperatorModel();
					bom.setOperatorID(String.valueOf(session.getAttribute("userid")));
					ResultSet rs = null;
					rs = bom.getOperatorData();
					while (rs.next()) {
			
      out.write("\n");
      out.write("\n");
      out.write("			<div class=\"centerform col-lg-12 col-md-12 col-sm-12c col-xs-12\">\n");
      out.write("				<form name=\"EditProfileFormController\" action=\"EditProfileFormController\" onsubmit=\"return validateLogin9();\" method=\"post\">\n");
      out.write("					<div class=\"form-group\">\n");
      out.write("						<label for=\"email\">EMail</label> <input type=\"text\" name=\"email\"\n");
      out.write("							class=\"form-control\" value=\"");
      out.print(rs.getString(4));
      out.write("\" />\n");
      out.write("							 <input type=\"hidden\" name=\"lastname\"  value=\"");
      out.print(rs.getString(4));
      out.write("\" />\n");
      out.write("							 <input type=\"hidden\" name=\"type\"  value=\"busOperator\" />\n");
      out.write("					</div>\n");
      out.write("					<div class=\"form-group\">\n");
      out.write("						<label for=\"firstname\">Name</label> <input type=\"text\"\n");
      out.write("							name=\"firstname\" class=\"form-control\" value=\"");
      out.print(rs.getString(2));
      out.write("\" />\n");
      out.write("					</div>\n");
      out.write("					<div class=\"form-group\">\n");
      out.write("						<label for=\"address\">Address</label> <input type=\"text\"\n");
      out.write("							name=\"address\" class=\"form-control\" value=\"");
      out.print(rs.getString(3));
      out.write("\" />\n");
      out.write("					</div>\n");
      out.write("					<div class=\"form-group\">\n");
      out.write("						<label for=\"city\">City</label> <input type=\"text\" name=\"city\"\n");
      out.write("							class=\"form-control\" value=\"");
      out.print(rs.getString(5));
      out.write("\" />\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("					<div class=\"form-group\">\n");
      out.write("						<label for=\"phonenumber\">Phone Number</label> <input type=\"text\"\n");
      out.write("							name=\"phonenumber\" class=\"form-control\"\n");
      out.write("							value=\"");
      out.print(rs.getString(6));
      out.write("\" />\n");
      out.write("					</div>\n");
      out.write("					<div class=\"form-group\">\n");
      out.write("						<button type=\"submit\" class=\"btn btn-danger\">Update</button>\n");
      out.write("					</div>\n");
      out.write("					");

						}
						}
					
      out.write("\n");
      out.write("				</form>				\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("	\n");
      out.write("\n");
      out.write("	<!-- ********************************* -->\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "layout/Footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
