/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-05-19 07:31:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import javax.servlet.http.*;
import com.cognizant.model.BusModel;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("com.cognizant.model.BusModel");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/flexselect.css\" type=\"text/css\" media=\"screen\" />\n");
      out.write("\n");
      out.write("<!--for form validation-->\n");
      out.write("<script type=\"text/javascript\" src=\"assets/js/blank.js\"></script>\n");
      out.write("\n");
      out.write("<script src=\"assets/js/jquery.min.js\" type=\"text/javascript\"></script> \n");
      out.write("<script src=\"assets/js/liquidmetal.js\" type=\"text/javascript\"></script>\n");
      out.write("<script src=\"assets/js/jquery.flexselect.js\" type=\"text/javascript\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    $(document).ready(function () {\n");
      out.write("        $(\"select.flexselect\").flexselect();\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<!--for calender-->\n");
      out.write("<script>\n");
      out.write("    jQuery(function () {\n");
      out.write("        jQuery(\"#inf_custom_someDateField\").datepicker();\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("    document.onkeydown = function (event) {\n");
      out.write("\n");
      out.write("        if (!event) { /* This will happen in IE */\n");
      out.write("            event = window.event;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        var keyCode = event.keyCode;\n");
      out.write("\n");
      out.write("        if (keyCode == 8 &&\n");
      out.write("                ((event.target || event.srcElement).tagName != \"TEXTAREA\") &&\n");
      out.write("                ((event.target || event.srcElement).tagName != \"INPUT\")) {\n");
      out.write("\n");
      out.write("            if (navigator.userAgent.toLowerCase().indexOf(\"msie\") == -1) {\n");
      out.write("                event.stopPropagation();\n");
      out.write("            } else {\n");
      out.write("                alert(\"prevented\");\n");
      out.write("                event.returnValue = false;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            return false;\n");
      out.write("        }\n");
      out.write("    };\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "layout/Header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<!-- ***********   START   *********** -->\n");
      out.write("\n");
      out.write("<!--show message coming from java class-->\n");
      out.write("<div class=\"mymainWrapper col-lg-12 col-md-12 col-sm-12 col-xs-12\">\n");
      out.write("    <div  class=\"errordiv col-lg-10 col-md-10 col-sm-10 col-xs-10\">\n");
      out.write("        ");

            if (request.getParameter("msg") != null) {
        
      out.write("\n");
      out.write("        <h4 style=\"color:black;\">");
      out.print(request.getParameter("msg"));
      out.write("</h4>\n");
      out.write("        ");

            }
        
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!--searching bus-->\n");
      out.write("    <div class=\"leftWrapper col-lg-6 col-md-6 col-sm-12 col-xs-12\">\n");
      out.write("        <div class=\"centertitle row col-lg-12 col-md-12 col-sm-12 col-xs-12\">\n");
      out.write("            CHOOSE YOUR DESTINATION</div>\n");
      out.write("        <div class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12 col-lg-offset-2\">\n");
      out.write("            <form name=\"SearchBusFormController\" action=\"SearchBusFormController\"\n");
      out.write("                  onsubmit=\"return validateLogin12();\" method=\"post\">\n");
      out.write("\n");
      out.write("                <div class=\"form-group col-lg-8 col-md-7 col-sm-10 col-xs-10\">\n");
      out.write("                    <label for=\"from\">From</label>\n");
      out.write("                    <select name=\"from\" id=\"from\" class=\"form-control\">						\n");
      out.write("                        <option value=\"\"></option>\n");
      out.write("                        ");

                            BusModel model = new BusModel();
                            ResultSet rs = model.getBusInfo1(1);

                            while (rs.next()) {
      out.write("\n");
      out.write("\n");
      out.write("                        <option value=\"");
      out.print(rs.getString(1));
      out.write('"');
      out.write('>');
      out.print(rs.getString(1).toUpperCase());
      out.write("</option>\n");
      out.write("                        ");
} 
      out.write("\n");
      out.write("                    </select>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group col-lg-8 col-md-7 col-sm-10 col-xs-10\">\n");
      out.write("                    <label for=\"to\">To</label>\n");
      out.write("                    <select name=\"to\" id=\"to\" class=\"form-control\">\n");
      out.write("                        <option value=\"\"></option>\n");
      out.write("                        ");

                            ResultSet rs1 = model.getBusInfo1(2);

                            while (rs1.next()) {
      out.write("\n");
      out.write("                        <option value=\"");
      out.print(rs1.getString(1));
      out.write('"');
      out.write('>');
      out.print(rs1.getString(1).toUpperCase());
      out.write("</option>\n");
      out.write("                        ");
}
      out.write("\n");
      out.write("                    </select>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group col-lg-8 col-md-7 col-sm-10 col-xs-10\">\n");
      out.write("                    <label for=\"from\">Date</label>\n");
      out.write("                    <!-- <input type=\"text\"\n");
      out.write("                            class=\"form-control\" id=\"date\" name=\"date\"> -->\n");
      out.write("                    <input class=\"tcal\" type=\"text\" name=\"date\" />\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group col-lg-8 col-md-7 col-sm-10 col-xs-10\">\n");
      out.write("                    <button type=\"submit\"\n");
      out.write("                            class=\"btn btn-success col-lg-5 col-md-5 col-sm-5 col-xs-5\"\n");
      out.write("                            style=\"float: left\">Search Buses</button>\n");
      out.write("                    <button type=\"reset\"\n");
      out.write("                            class=\"btn btn-warning col-lg-5 col-md-5 col-sm-5 col-xs-5\"\n");
      out.write("                            style=\"float: right\">Clear</button>\n");
      out.write("                </div>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!--  End of left wrapper -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!--Login Part-->\n");
      out.write("    <div class=\"rightWrapper col-lg-5 col-md-5 col-sm-12 col-xs-12\">\n");
      out.write("        <div class=\"centertitle row col-lg-12 col-md-12 col-sm-12 col-xs-12\">\n");
      out.write("            LOGIN</div>\n");
      out.write("        <div class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12  col-lg-offset-2\">\n");
      out.write("            <form name=\"LoginFormController\" action=\"LoginFormController\"\n");
      out.write("                  onsubmit=\"return validateLogin13();\" method=\"post\">\n");
      out.write("\n");
      out.write("                <div class=\"form-group col-lg-8 col-md-7 col-sm-10 col-xs-10\">\n");
      out.write("                    <label for=\"from\">Email</label> <input type=\"text\" id=\"email\"\n");
      out.write("                                                           class=\"form-control text required email\" id=\"email\"\n");
      out.write("                                                           name=\"username\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group col-lg-8 col-md-7 col-sm-10 col-xs-10\">\n");
      out.write("                    <label for=\"password\">Password</label> <input type=\"password\"\n");
      out.write("                                                                  class=\"form-control\" id=\"password\" name=\"password\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <input type=\"hidden\" name=\"type\" value=\"user\" />\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group col-lg-8 col-md-7 col-sm-10 col-xs-10\">\n");
      out.write("                    <button type=\"submit\"\n");
      out.write("                            class=\"btn btn-success col-lg-5 col-md-5 col-sm-5 col-xs-5\"\n");
      out.write("                            style=\"float: left\">Login</button>\n");
      out.write("                    <button type=\"reset\"\n");
      out.write("                            class=\"btn btn-warning col-lg-5 col-md-5 col-sm-5 col-xs-5\"\n");
      out.write("                            style=\"float: right\">Clear</button>\n");
      out.write("                </div>\n");
      out.write("            </form>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"centertitle forgotpwd col-lg-8 col-md-7 col-sm-10 col-xs-10 col-lg-offset-2\">\n");
      out.write("            <a href=\"ForgotPassword1.jsp\">Forgot Password? Click Here</a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"centertitle logOptions col-lg-12 col-md-12 col-sm-12 col-xs-12\">\n");
      out.write("            <a href=\"BusOperatorLogin.jsp\">Login as Bus Operator </a> | <a href=\"RegisterUser.jsp\"> Sign Up</a> | <a href=\"AdminLogin.jsp\">Admin Login</a>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "layout/Footer.jsp", out, false);
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
